package main.G1HRPS;

import java.util.UUID;

public class Payment {
	/**
	 * Unique generated ID
	 */
	private final UUID payment_id_;
	private int guest_id_;
	private float discounts_;
	private float tax_;
	private float bill_total_;
	private PaymentStatus status_;

	/**
	 * Payment Constructor.
	 * @param id UUID generated by manager
	 * @param guest_id
	 * @param discounts
	 * @param bill_total After deducting discounts
	 * @param status
	 */
	public Payment(UUID id, int guest_id, float discounts, float tax, float bill_total, PaymentStatus status) {
		payment_id_ = id;
		guest_id_ = guest_id;
		discounts_ = discounts;
		tax_ = tax;
		bill_total_ = bill_total;
		status_ = status;

	}

	/**
	 * 
	 * @param guest_id
	 */
	public void SetGuestId(int guest_id) {
		// TODO - implement Payment.SetGuestId

		this.guest_id_ = guest_id;

		throw new UnsupportedOperationException();
	}

	public void SetDiscount(float discount) {
		// TODO - implement Payment.SetDiscount

		this.discounts_ = discount;

		throw new UnsupportedOperationException();
	}

	public void SetRoomCharges() {
		// TODO - implement Payment.SetRoomCharges



		throw new UnsupportedOperationException();
	}

	public void SetRoomServices() {
		// TODO - implement Payment.SetRoomServices



		throw new UnsupportedOperationException();
	}

	/**
	 * 
	 * @param Tax
	 */
	public void SetTax(float Tax) {
		// TODO - implement Payment.SetTax

		this.tax_ = Tax;

		throw new UnsupportedOperationException();
	}

	/**
	 * 
	 * @param bill_total
	 */
	public void SetBillTotal(float bill_total) {
		// TODO - implement Payment.SetBillTotal

		this.bill_total_ = bill_total;

		throw new UnsupportedOperationException();
	}

	/**
	 * 
	 * @param status
	 */
	public void SetStatus(PaymentStatus status) {
		// TODO - implement Payment.SetStatus

		this.status_ = status;

		throw new UnsupportedOperationException();
	}

	public int GetGuestId() {
		// TODO - implement Payment.GetGuestId

		return guest_id_;

		// throw new UnsupportedOperationException();
	}

	public float GetDiscount() {
		// TODO - implement Payment.GetDiscount

		return this.discounts_;

		// throw new UnsupportedOperationException();
	}

	public void GetRoomCharges() {
		// TODO - implement Payment.GetRoomCharges
		
		

		throw new UnsupportedOperationException();
	}

	public void GetRoomServices() {
		// TODO - implement Payment.GetRoomServices

		throw new UnsupportedOperationException();
	}

	public float GetTax() {
		// TODO - implement Payment.GetTax

		return this.tax_;
		
		// throw new UnsupportedOperationException();
	}

	public float SetBillTotal() {
		// TODO - implement Payment.SetBillTotal



		throw new UnsupportedOperationException();
	}

	public PaymentStatus GetStatus() {
		// TODO - implement Payment.GetStatus

		return this.status_;

		// throw new UnsupportedOperationException();
	}

	public UUID GetPaymentID(){
		// TODO - implement Payment.GetPaymentID

		return this.payment_id_;
	}

	public float GetTotalBill(){
		// TODO - implement Payment.GetTotalBill

		return this.bill_total_;
	}
}