package main.G1HRPS;

import java.util.UUID;
import java.util.List;

public class Payment {
	/**
	 * Unique generated ID
	 */
	private final UUID payment_id_;
	private String guest_id_;
	private int room_num_;
	private float discounts_;
	private float tax_;
	private float room_charges_;
	private float rs_charges_;
	private float bill_total_;
	private PaymentStatus status_;

	/**
	 * Payment Constructor.
	 * 
	 * @param id         UUID generated by manager
	 * @param guest_id
	 * @param room_num
	 * @param discounts
	 * @param bill_total After deducting discounts
	 * @param status
	 */
	public Payment(UUID id, String guest_id, int room_num, float discounts, float tax, float bill_total, PaymentStatus status) {
		payment_id_ = id;
		guest_id_ = guest_id;
		room_num_ = room_num;
		discounts_ = discounts;
		tax_ = tax;
		room_charges_ = 0;
		rs_charges_ = 0;
		bill_total_ = bill_total;
		status_ = status;
	}

	public UUID GetPaymentID(){

		return payment_id_;

	}

	/**
	 * 
	 * @param guest_id
	 */
	public void SetGuestID(String guest_id) {

		guest_id_ = guest_id;

	}


	public String GetGuestID() {
		
		return guest_id_;

	}

	public void SetRoomNum(int room_num) {

		room_num_ = room_num;

	}

	public int GetRoomNum() {

		return room_num_;
		
	}

	public void SetDiscount(float discount) {

		discounts_ = discount;

	}

	public float GetDiscount() {

		return discounts_;

	}

	public void SetRoomCharges(float room_charges) {

		room_charges_ = room_charges;

	}

	public float GetRoomCharges() {
		
		return room_charges_;

	}

	public void SetRsCharges(float rs_charges) {

		rs_charges_ = rs_charges;

	}

	/**
	 * 
	 * @param room_service_order_list
	 */

	public void SetRsCharges(List<RoomServiceOrder> room_service_order_list) {

		int room_num;
		float rs_charges = 0;

		for(RoomServiceOrder rsOrder : room_service_order_list){
			room_num = rsOrder.GetRoomNum();
			if(this.room_num_ == room_num){
				rs_charges += rsOrder.CalTotalPrice();
			}
		}

		rs_charges_ = rs_charges;

	}

	public float GetRsCharges() {

		return rs_charges_;

	}

	/**
	 * 
	 * @param Tax
	 */
	public void SetTax(float tax) {
		// TODO - implement Payment.SetTax

		tax_ = tax;

	}

	public float GetTax() {

		return tax_;
		
	}

	/**
	 * 
	 * @param bill_total
	 */
	public void SetBillTotal(float bill_total) {
		// TODO - implement Payment.SetBillTotal

		bill_total_ = bill_total;

	}

	public float SetBillTotal() {

		bill_total_ = ((room_charges_ + rs_charges_) * (1-discounts_)) * (1 + tax_);

		return bill_total_;

	}

	public float GetTotalBill(){

		return bill_total_;

	}

	/**
	 * 
	 * @param status
	 */
	public void SetStatus(PaymentStatus status) {

		status_ = status;

	}

	public PaymentStatus GetStatus() {

		return status_;

	}
}