package main.G1HRPS;

import java.util.UUID;
import java.util.List;

public class Payment {
	/**
	 * Unique generated ID
	 */
	private final UUID payment_id_;
	private int room_num_;
	private float discounts_;
	private float tax_;
	private float room_charges_;
	private float rs_charges_;
	private float bill_total_;
	private PaymentStatus status_;

	/**
	 * Payment Constructor.
	 * 
	 * @param id         UUID generated by manager
	 * @param guest_id
	 * @param discounts
	 * @param bill_total After deducting discounts
	 * @param status
	 */
	public Payment(UUID id, int room_num, float discounts, float tax, float bill_total, PaymentStatus status) {
		payment_id_ = id;
		room_num_ = room_num;
		discounts_ = discounts;
		tax_ = tax;
		room_charges_ = 0;
		rs_charges_ = 0;
		bill_total_ = bill_total;
		status_ = status;
	}

	/**
	 * 
	 * @param guest_id
	 */
	public void SetRoomNum(int room_num) {

		room_num_ = room_num;

	}

	public void SetDiscount(float discount) {

		discounts_ = discount;

	}

	public void SetRoomCharges(float room_charges) {

		room_charges_ = room_charges;

	}

	/**
	 * 
	 * @param room_service_order_list
	 */

	public void SetRoomServices(List<RoomServiceOrder> room_service_order_list) {
		// TODO - Find a straightforward way to get total cost of each rso

		int room_num;

		for(RoomServiceOrder rsOrder : room_service_order_list){
			room_num = rsOrder.GetRoomNum();
			if(this.room_num_ == room_num){
				// rs_charges_ += rsOrder.
			}
		}

	}

	/**
	 * 
	 * @param Tax
	 */
	public void SetTax(float Tax) {
		// TODO - implement Payment.SetTax

		tax_ = Tax;

		throw new UnsupportedOperationException();
	}

	/**
	 * 
	 * @param bill_total
	 */
	public void SetBillTotal(float bill_total) {
		// TODO - implement Payment.SetBillTotal

		bill_total_ = bill_total;

		throw new UnsupportedOperationException();
	}

	/**
	 * 
	 * @param status
	 */
	public void SetStatus(PaymentStatus status) {

		status_ = status;

	}

	public int GetRoomNum() {

		return room_num_;
		
	}

	public float GetDiscount() {

		return discounts_;

	}

	public float GetRoomCharges() {
		
		return room_charges_;

	}

	public float GetRsCharges() {

		return rs_charges_;

	}

	public float GetTax() {

		return tax_;
		
	}

	public float SetBillTotal() {

		bill_total_ = ((room_charges_ + rs_charges_) * (1-discounts_)) * (1 + tax_);

		return bill_total_;

	}

	public PaymentStatus GetStatus() {

		return status_;

	}

	public UUID GetPaymentID(){

		return payment_id_;

	}

	public float GetTotalBill(){

		return bill_total_;

	}
}